<?php

namespace AppBundle\Repository;

/**
 * CinescenieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CinescenieRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByUserAndDateGreaterThan($user, $date)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            '
            SELECT c
            FROM AppBundle:Cinescenie c
            JOIN c.schedules s WITH (s.user = :user)
            WHERE c.date > :date
            ORDER BY c.date ASC
            '
        )->setParameters([
        	'user' => $user,
            'date' => $date,
        ]);
        $cinescenies = $query->getResult();

        return $cinescenies;
    }

    public function getByDateGreaterThan($date)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            '
            SELECT c
            FROM AppBundle:Cinescenie c
            WHERE c.date >= :date
            ORDER BY c.date ASC
            '
        )->setParameters([
            'date' => $date,
        ]);
        $cinescenies = $query->getResult();

        return $cinescenies;
    }

    public function getCinesceniesBetween($from, $to)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            '
            SELECT c
            FROM AppBundle:Cinescenie c
            WHERE c.date > :from AND c.date < :to
            ORDER BY c.date ASC
            '
        )->setParameters([
            'from' => $from,
            'to'   => $to,
        ]);
        $cinescenies = $query->getResult();

        return $cinescenies;
    }
}
