<?php

namespace AppBundle\Repository;

/**
 * CinescenieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CinescenieRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByUser($user)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            '
            SELECT c
            FROM AppBundle:Cinescenie c
            JOIN c.schedules s WITH (s.user = :user)
            '
        )->setPArameters([
        	'user' => $user
        ]);
        $cinescenies = $query->getResult();

        return $cinescenies;
    }
}
