<?php

namespace AppBundle\Repository;

/**
 * CinescenieStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CinescenieStateRepository extends \Doctrine\ORM\EntityRepository
{
}
