<?php

namespace AppBundle\Repository;

/**
 * CinescenieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CinescenieRepository extends \Doctrine\ORM\EntityRepository
{
}
