<?php

namespace AppBundle\Repository;

/**
 * GroupActivitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupActivitiesRepository extends \Doctrine\ORM\EntityRepository
{
}
