<?php

namespace AppBundle\Repository;

/**
 * MemberSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
