<?php

namespace AppBundle\Repository;

/**
 * MemberSpecialtyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberSpecialtyRepository extends \Doctrine\ORM\EntityRepository
{
}
