<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Cinescenie;
use AppBundle\Entity\User;

/**
 * ScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastActivity(User $user)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            '
            SELECT s
            FROM AppBundle:Schedule s
            JOIN s.activity a
            JOIN s.cinescenie c WITH (c.state = :state)
            WHERE s.user = :user
            ORDER BY c.date DESC
            '
        )->setParameters([
            'state' => Cinescenie::STATE_VALIDATE,
            'user'  => $user
        ]);
        $schedules = $query->getResult();

        return $schedules;
    }

    public function getWithoutActivity(Cinescenie $cinescenie)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            '
            SELECT s
            FROM AppBundle:Schedule s
            WHERE s.activity IS NULL
            AND s.cinescenie = :cinescenie
            '
        )->setParameters([
            'cinescenie' => $cinescenie,
        ]);
        $schedules = $query->getResult();

        return $schedules;
    }
}
