<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Member;

/**
 * ScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastActivity($member, $from, $to)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            '
            SELECT s
            FROM AppBundle:Schedule s
            JOIN s.cinescenie c WITH (c.date > :from AND c.date < :to)
            WHERE s.member = :member
            AND s.activity IS NOT NULL
            ORDER BY c.date DESC
            '
        )->setParameters([
            'member'  => $member,
            'from'    => $from,
            'to'      => $to,
        ]);
        $schedules = $query->getResult();

        return $schedules;
    }

    public function getLastSpecialty(Member $member, $from, $to)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            '
            SELECT s
            FROM AppBundle:Schedule s
            JOIN s.cinescenie c WITH (c.date > :from AND c.date < :to)
            WHERE s.member = :member
            ORDER BY c.date DESC
            '
        )->setParameters([
            'member' => $member,
            'from'   => $from,
            'to'     => $to,
        ]);
        $schedules = $query->getResult();

        return $schedules;
    }

    public function getWithoutActivity($cinescenies)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            '
            SELECT s
            FROM AppBundle:Schedule s
            WHERE s.activity IS NULL
            AND s.cinescenie IN (:cinescenies)
            '
        )->setParameters([
            'cinescenies' => $cinescenies,
        ]);
        $schedules = $query->getResult();

        return $schedules;
    }
}
