<?php

namespace AppBundle\Repository;

/**
 * SkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByUser($user)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            '
            SELECT s
            FROM AppBundle:Skill s
            JOIN s.userSkills us WITH (us.user = :user)
            '
        )->setPArameters([
        	'user' => $user
        ]);
        $skills = $query->getResult();

        return $skills;
    }
}
