<?php

namespace AppBundle\Repository;

/**
 * SkillActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillActivityRepository extends \Doctrine\ORM\EntityRepository
{
}
