<?php

namespace AppBundle\Repository;

/**
 * SpecialtyActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialtyActivityRepository extends \Doctrine\ORM\EntityRepository
{
}
