<?php

namespace AppBundle\Repository;

/**
 * UserAuthorizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAuthorizationRepository extends \Doctrine\ORM\EntityRepository
{
}
