<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Cinescenie;

/**
 * RealPresenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getForDivision(Cinescenie $cinescenie, $skillsId)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            '
            SELECT u, COUNT(sc.id) AS totalSchedules
            FROM AppBundle:User u
            JOIN u.userSkills us WITH us.skill IN (:skills)
            JOIN us.skill s
            JOIN s.skillActivities sa
            JOIN sa.activity a
            LEFT JOIN a.schedules sc WITH (sc.user = u)
            JOIN u.schedules sc2 WITH (sc2.cinescenie = :cinescenie)
            GROUP BY u.id
            ORDER BY totalSchedules ASC
            '
        )->setParameters([
            'skills'     => $skillsId,
            'cinescenie' => $cinescenie,
        ]);
        $users = $query->getResult();

        return $users;
    }
}
