app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_user_security_login:
    path: /identification
    defaults: { _controller: FOSUserBundle:Security:login }
    requirements:
        _method: GET|POST